#!/bin/bash
# c2mos_margin.sh <setup|hold>
#
# Preliminary setup / hold scan of the single C^2MOS DFF, in ONE spectre run:
# every margin gets its own identical cell instance with its own data source, all
# sharing the single clock. 12 margins therefore cost one simulation, not twelve,
# and all instances see exactly the same clock edges.
#
# Tested edge = the third rising edge (2.5T). The two earlier edges are prime edges
# that give each slave keeper a defined state (T fixed at 200 ns here, because
# setup/hold are set by internal delays, not by the period).
#
#   setup : d rises at 2.5T - MARGIN   -> q must reach VDD in [2.7T,2.95T]  = CAPTURED
#   hold  : d falls at 2.5T + MARGIN   -> q must stay at VDD in [2.7T,2.95T] = HELD
#   a negative margin moves the data edge to the "wrong" side of the clock edge,
#   which is what brackets the boundary.
#
# Nothing here is a hard spec number: it is the first-order characterisation the
# course POC asks for, at one load capacitance (50 fF, TESTBENCH ASSUMPTION).
set -u

PROJ="${PROJ:-/root/microled_ai_project}"
MODE="${1:?usage: c2mos_margin.sh <setup|hold>}"
RS="$PROJ/scripts/run_spectre.sh"
AWK="$PROJ/scripts/psf_check.awk"
LOGD="$PROJ/logs"
CELL="$PROJ/spectre/C2MOS_DFF.scs"

case "$MODE" in setup|hold) ;; *) echo "FATAL: mode must be setup or hold"; exit 8 ;; esac
[ -r "$CELL" ] || { echo "FATAL: cell missing $CELL"; exit 8; }

T=2e-7
V=1.8
EDGE=$(awk -v t="$T" 'BEGIN{printf "%.9g", 2.5*t}')      # the tested rising edge
W0=$(awk -v t="$T" 'BEGIN{printf "%.9g", 2.7*t}')         # verdict window start
W1=$(awk -v t="$T" 'BEGIN{printf "%.9g", 2.95*t}')        # verdict window end
D0=$(awk -v t="$T" 'BEGIN{printf "%.9g", 0.2*t}')         # hold mode: d rises here

# margins in seconds, coarse to fine, then past the boundary
MARGINS=(20e-9 10e-9 5e-9 3e-9 2e-9 1.5e-9 1e-9 0.7e-9 0.4e-9 0.2e-9 0 -0.4e-9 -1e-9)

NET="$PROJ/spectre/margin_${MODE}.scs"
DIRS="$LOGD/margin_dirs_${MODE}.txt"
ASS="$LOGD/margin_assert_${MODE}.txt"
RUN="$LOGD/margin_run_${MODE}.out"

{
  echo "// GENERATED by scripts/c2mos_margin.sh -- mode=$MODE, T=$T, tested edge=$EDGE"
  echo "// one instance per margin; identical cells, identical loads, shared clock"
  echo "simulator lang=spectre insensitive=yes"
  # emitted as literals on purpose: Spectre expands ${QODER_PDK_LIB} from the
  # environment, and run_spectre.sh loads that variable from the untracked
  # spectre/pdk_local.env, so no vendor path is ever written into a committed file
  echo 'include "${QODER_PDK_LIB}" section=tt'
  echo 'include "C2MOS_DFF.scs"'
  echo ""
  echo "Vdd (vdd 0) vsource dc=$V"
  # vss must be tied to ground: inside the cell it only touches sources and bulks, so
  # a floating vss means no NMOS current and a cell that never switches
  echo "Vss (vss 0) vsource dc=0"
  echo "Ck (clk 0) vsource type=pulse val0=0 val1=$V period=$T delay=$(awk -v t="$T" 'BEGIN{printf "%.9g",0.5*t}') width=$(awk -v t="$T" 'BEGIN{printf "%.9g",0.5*t}') rise=1e-9 fall=1e-9"
  echo ""
} > "$NET"

: > "$DIRS"
i=0
for m in "${MARGINS[@]}"; do
  if [ "$MODE" = "setup" ]; then
    dly=$(awk -v e="$EDGE" -v x="$m" 'BEGIN{printf "%.9g", e-x}')
    wid="1e-4"
  else
    dly="$D0"
    wid=$(awk -v e="$EDGE" -v x="$m" -v d="$D0" 'BEGIN{printf "%.9g", e+x-d}')
  fi
  cat >> "$NET" <<EOF
D$i (d$i 0) vsource type=pulse val0=0 val1=$V period=1 delay=$dly width=$wid rise=1e-9 fall=1e-9
X$i (d$i clk q$i qb$i vdd vss) c2mos_dff
Cq$i  (q$i  0) capacitor c=50e-15
Cqb$i (qb$i 0) capacitor c=50e-15
EOF
  echo "ASSERT q$i $W0 $W1 gt 1.5" >> "$DIRS"
  echo "save d$i q$i" >> "$NET"
  i=$((i+1))
done
N=$i
{
  echo ""
  echo "save clk"
  echo "tr1 tran stop=$(awk -v t="$T" 'BEGIN{printf "%.9g",3.5*t}') maxstep=2e-11"
} >> "$NET"

echo "mode=$MODE instances=$N netlist=$NET"
LABEL="MARGIN_${MODE}" bash "$RS" "$NET" 500 > "$RUN" 2>&1
rc=$?
DATA=$(grep -aoE "CHECK datafile='[^']+'" "$RUN" | sed -E "s/.*'(.*)'/\1/")
if [ "$rc" != "0" ] || [ -z "$DATA" ] || [ ! -r "$DATA" ]; then
  echo "MARGIN_SWEEP[$MODE]: FAIL stage=spectre rc=$rc"
  grep -aE "^SPECTRE name|ERROR \(|^CHECK error_hits" "$RUN" | head -6
  tail -18 "$RUN"
  exit 1
fi
awk -f "$AWK" "$DIRS" "$DATA" > "$ASS"

# join the margin list with the ordered assertion results
res=()
while IFS= read -r line; do res+=("$line"); done < <(grep -aE "^(OK|FAIL) +ASSERT" "$ASS")
echo "assert_lines=${#res[@]} instances=$N"
if [ "${#res[@]}" != "$N" ]; then
  echo "MARGIN_SWEEP[$MODE]: FAIL stage=assert_coverage got=${#res[@]} want=$N"
  cat "$ASS"
  exit 1
fi
printf "%-9s %-12s %-9s %-9s %s\n" "margin_ns" "q_min_V" "q_max_V" "verdict" "window"
pass_min=""; fail_max=""
i=0
for m in "${MARGINS[@]}"; do
  line="${res[$i]:-}"
  mn=$(echo "$line" | sed -E 's/.*min=([-0-9.eE+]+).*/\1/')
  mx=$(echo "$line" | sed -E 's/.*max=([-0-9.eE+]+).*/\1/')
  case "$line" in
    OK*)  v=PASS;;
    FAIL*) if awk -v a="$mx" 'BEGIN{exit (a<0.3)?0:1}'; then v=NEG; else v=AMB; fi;;
    *) v=MISS;;
  esac
  if [ "$MODE" = "setup" ]; then
    [ "$v" = "PASS" ] && v=CAPTURED; [ "$v" = "NEG" ] && v=REJECTED
  else
    [ "$v" = "PASS" ] && v=HELD;      [ "$v" = "NEG" ] && v=LOST
  fi
  mns=$(awk -v x="$m" 'BEGIN{printf "%8.3f", x*1e9}')
  printf "%-9s %-12s %-9s %-9s %s\n" "$mns" "$mn" "$mx" "$v" "[${W0},${W1}]"
  if [ "$v" = "CAPTURED" ] || [ "$v" = "HELD" ]; then
    # boundary = SMALLEST margin that still works; this list runs large to small,
    # so keep overwriting while it passes
    pass_min="$m"
  elif [ "$v" = "REJECTED" ] || [ "$v" = "LOST" ]; then
    fail_max="$m"
  fi
  i=$((i+1))
done
if [ -z "$pass_min" ]; then
  echo "MARGIN_SWEEP[$MODE]: no margin passed -- see the table above"
  exit 1
fi
pn=$(awk -v x="$pass_min" 'BEGIN{printf "%.3f", x*1e9}')
if [ -z "$fail_max" ]; then fn="none"; else fn=$(awk -v x="$fail_max" 'BEGIN{printf "%.3f", x*1e9}'); fi
echo "OBSERVED: smallest working margin = ${pn} ns; largest failing margin = ${fn} ns"
if [ "$fn" = "none" ]; then
  echo "  -> no ${MODE} violation inside the scan range; q stayed at 1.8000 V (zero droop)"
else
  echo "  -> ${MODE} time is bracketed in (${fn}, ${pn}] ns  (T=$T, Cload=50 fF, 1 ns edges)"
fi
echo "MARGIN_SWEEP[$MODE]: DONE  log=$RUN  assert=$ASS"
