#!/bin/bash
# c2mos_margin.sh -- PRELIMINARY setup / hold scan of the single C^2MOS DFF.
#
#   c2mos_margin.sh <setup|hold> [slew_seconds] [tag]
#
# Slew defaults to 1e-9 (the 1 ns source edges used in the first POC). Pass 5e-11 for
# the 50 ps comparison run the review asked for: if the boundary moves with the source
# slew, the slew -- not the cell -- is setting the answer, and no timing number may be
# quoted as a cell property.
#
# What changed versus the first version (review finding A5): the margin is no longer
# read off the voltage-source `delay` parameter. Every point now extracts the real 50 %
# crossings from the waveforms
#
#     t_D50   = d<i>  crossing VTH = 0.5*VDD
#     t_CLK50 = clk   crossing VTH at the tested edge
#     t_Q50   = q<i>  crossing VTH after that edge
#
# and reports the MEASURED spacing  t_CLK50 - t_D50  (how long the data input was
# actually settled before the capturing edge) together with  t_Q50 - t_CLK50  (clk->Q).
# Source delay is only the knob; it is not a threshold-to-threshold margin, because the
# 1 ns / 50 ps ramp eats part of it.
#
# Structure: one identical cell instance per margin, each with its own data source, all
# sharing one clock, so the whole scan costs a single simulation and every instance sees
# identical clock edges. The tested edge is the third rising edge (2.5T); the two before
# it are prime edges that give each slave keeper a defined state (the cell has no reset,
# so this is a simulation-initialisation concern, not a design feature).
#
# Output is a CSV plus a bracket statement. Nothing here is a spec: it is preliminary
# characterisation at one corner (tt), one temperature, one load (50 fF), one VDD.
set -u

PROJ="${PROJ:-/root/microled_ai_project}"
MODE="${1:?usage: c2mos_margin.sh <setup|hold> [slew] [tag]}"
SLEW="${2:-1e-9}"
TAG="${3:-s${SLEW}}"
RS="$PROJ/scripts/run_spectre.sh"
AWK="$PROJ/scripts/psf_check.awk"
PF="$PROJ/scripts/tb_preflight.sh"
LOGD="$PROJ/logs"
CELL="$PROJ/spectre/C2MOS_DFF.scs"

case "$MODE" in setup|hold) ;; *) echo "FATAL: mode must be setup or hold"; exit 8 ;; esac
[ -r "$CELL" ] || { echo "FATAL: cell missing $CELL"; exit 8; }

T=2e-7
V=1.8
VTH=$(awk -v v="$V" 'BEGIN{printf "%.9g", v*0.5}')       # 50 % of VDD, as required
EDGE=$(awk -v t="$T" 'BEGIN{printf "%.9g", 2.5*t}')       # the tested rising edge
W0=$(awk -v t="$T" 'BEGIN{printf "%.9g", 2.7*t}')          # verdict window start
W1=$(awk -v t="$T" 'BEGIN{printf "%.9g", 2.95*t}')         # verdict window end
D0=$(awk -v t="$T" 'BEGIN{printf "%.9g", 0.2*t}')          # hold mode: d rises here
CLK_T0=$(awk -v t="$T" 'BEGIN{printf "%.9g", 2.4*t}')      # search start for the edge

MARGINS=(20e-9 10e-9 5e-9 3e-9 2e-9 1.5e-9 1e-9 0.7e-9 0.4e-9 0.2e-9 0 -0.4e-9 -1e-9)

NET="$PROJ/spectre/margin_${MODE}_${TAG}.scs"
DIRS="$LOGD/margin_dirs_${MODE}_${TAG}.txt"
ASS="$LOGD/margin_assert_${MODE}_${TAG}.txt"
RUN="$LOGD/margin_run_${MODE}_${TAG}.out"
CSV="$LOGD/margin_${MODE}_${TAG}.csv"

# ------------------------------------------------------------------ generate ----
{
  echo "// GENERATED by scripts/c2mos_margin.sh -- mode=$MODE T=$T slew=$SLEW VTH=$VTH"
  echo "// one instance per margin; identical cells, identical loads, shared clock."
  echo "// PRELIMINARY characterisation: tt corner, one VDD, one temperature, 50 fF."
  echo "simulator lang=spectre insensitive=yes"
  echo 'include "${QODER_PDK_LIB}" section=tt'
  echo 'include "C2MOS_DFF.scs"'
  echo ""
  echo "Vdd (vdd 0) vsource dc=$V"
  # vss must be tied to ground: inside the cell it only touches sources and bulks, so
  # a floating vss means no NMOS current and a cell that never switches
  echo "Vss (vss 0) vsource dc=0"
  echo "Ck (clk 0) vsource type=pulse val0=0 val1=$V period=$T delay=$(awk -v t="$T" 'BEGIN{printf "%.9g",0.5*t}') width=$(awk -v t="$T" 'BEGIN{printf "%.9g",0.5*t}') rise=$SLEW fall=$SLEW"
  echo ""
} > "$NET"

: > "$DIRS"
i=0
for m in "${MARGINS[@]}"; do
  if [ "$MODE" = "setup" ]; then
    dly=$(awk -v e="$EDGE" -v x="$m" 'BEGIN{printf "%.9g", e-x}')
    wid="1e-4"
    dkind=CROSS
  else
    dly="$D0"
    # Spectre's pulse timeline is: rise STARTS at `delay`, the plateau of `width` begins
    # only once the rise has completed, then the fall starts. So to land the fall at
    # EDGE + margin the plateau must be shortened by one rise time.
    wid=$(awk -v e="$EDGE" -v x="$m" -v d="$D0" -v r="$SLEW" 'BEGIN{printf "%.9g", e+x-d-r}')
    dkind=FALL
  fi
  cat >> "$NET" <<EOF
D$i (d$i 0) vsource type=pulse val0=0 val1=$V period=1 delay=$dly width=$wid rise=$SLEW fall=$SLEW
X$i (d$i clk q$i qb$i vdd vss) c2mos_dff
Cq$i  (q$i  0) capacitor c=50e-15
Cqb$i (qb$i 0) capacitor c=50e-15
EOF
  # level verdict, then the three 50 % crossings this point is really about
  echo "ASSERT q$i $W0 $W1 gt 1.5" >> "$DIRS"
  if [ "$MODE" = "setup" ]; then
    echo "CROSS d$i $VTH 0" >> "$DIRS"
    echo "CROSS q$i $VTH $CLK_T0" >> "$DIRS"
  else
    echo "FALL d$i $VTH $CLK_T0" >> "$DIRS"
    echo "FALL q$i $VTH $CLK_T0" >> "$DIRS"
  fi
  echo "save d$i q$i" >> "$NET"
  i=$((i+1))
done
N=$i
# one shared clock crossing: the first clk 50% rise at/after the search start, i.e. the
# tested edge itself. Every instance's spacings are measured against this same instant.
echo "CROSS clk $VTH $CLK_T0" >> "$DIRS"
{
  echo ""
  echo "save clk"
  echo "tr1 tran stop=$(awk -v t="$T" 'BEGIN{printf "%.9g",3.5*t}') maxstep=2e-11"
} >> "$NET"

echo "mode=$MODE slew=$SLEW tag=$TAG instances=$N netlist=$NET"

# ------------------------------------------------------------------ preflight ---
pf_out=$(bash "$PF" "$NET" "$V" "margin_$MODE" 2>&1)
pf_rc=$?
echo "$pf_out" | grep -aE "STATIC_OK|STATIC_FAIL|OP_OK|OP_FAIL|RAIL_|TESTBENCH_PREFLIGHT" | sed 's/^/    /'
if [ "$pf_rc" != "0" ]; then
  echo "MARGIN_SWEEP[$MODE/$SLEW]: FAIL  (testbench preflight refused this sweep)"
  exit 1
fi

LABEL="MARGIN_${MODE}_${TAG}" bash "$RS" "$NET" 500 > "$RUN" 2>&1
rc=$?
DATA=$(grep -aoE "CHECK datafile='[^']+'" "$RUN" | sed -E "s/.*'(.*)'/\1/")
if [ "$rc" != "0" ] || [ -z "$DATA" ] || [ ! -r "$DATA" ]; then
  echo "MARGIN_SWEEP[$MODE/$SLEW]: FAIL stage=spectre rc=$rc"
  grep -aE "^SPECTRE name|ERROR \(|^CHECK error_hits" "$RUN" | head -6
  tail -18 "$RUN"
  exit 1
fi
awk -f "$AWK" "$DIRS" "$DATA" > "$ASS"
echo "crossing_search_start clk t0=$CLK_T0  tested edge=$EDGE  verdict window=[$W0,$W1]"

# ------------------------------------------------------------------- parse -----
# one row per margin: source knob, measured 50% crossings, measured spacings, verdict
{
  if [ "$MODE" = "setup" ]; then MARG="setup_margin_ns"; else MARG="hold_margin_ns"; fi
  echo "margin_source_ns,t_D50_ns,t_CLK50_ns,t_Q50_ns,$MARG,CLK50_to_Q50_ns,q_min_V,q_max_V,level_verdict,slew_ns"
  i=0
  for m in "${MARGINS[@]}"; do
    sig="q$i"
    lvl=$(grep -aE "^(OK|FAIL) +ASSERT +$sig " "$ASS" | head -1)
    qmin=$(echo "$lvl" | sed -E 's/.*min=([-0-9.eE+]+).*/\1/')
    qmax=$(echo "$lvl" | sed -E 's/.*max=([-0-9.eE+]+).*/\1/')
    case "$lvl" in OK*) verdict=PASS ;; *) verdict=FAIL ;; esac
    tx=$(grep -aE "^OK +(CROSS|FALL) +clk " "$ASS" | head -1 | sed -E 's/.*[ ]t=([-0-9.eE+]+).*/\1/')
    # CROSS|FALL only: the ASSERT lines carry the same signal name and would otherwise
    # be picked up here (that mistake silently produced t_Q50 = 0 for every row)
    dline=$(grep -aE "^(OK|FAIL) +(CROSS|FALL) +d$i " "$ASS" | head -1)
    qline=$(grep -aE "^(OK|FAIL) +(CROSS|FALL) +$sig " "$ASS" | head -1)
    td=""; tq=""
    case "$dline" in OK*) td=$(echo "$dline" | sed -E 's/.*[ ]t=([-0-9.eE+]+).*/\1/') ;; esac
    case "$qline" in OK*) tq=$(echo "$qline" | sed -E 's/.*[ ]t=([-0-9.eE+]+).*/\1/') ;; esac
    case "$tx" in ""|*[!0-9.eE+-]*) tx="" ;; esac
    awk -v m="$m" -v td="$td" -v tx="$tx" -v tq="$tq" -v qmin="$qmin" -v qmax="$qmax" \
        -v v="$verdict" -v sl="$SLEW" -v mode="$MODE" 'BEGIN{
      ns = 1e9
      # mawk aborts on 0/0 rather than producing NaN, so unmeasurable spacings are
      # written as the literal n/a and skipped by the bracket computation below
      have_d = (td != "" && tx != "")
      have_tx = (tx != "")
      have_q = (tq != "" && have_tx)
      # sign convention chosen so that BIGGER is always WORST-CASE-BETTER in both modes:
      #   setup_margin = t_CLK50 - t_D50  (data settled this long before the edge)
      #   hold_margin  = t_D50  - t_CLK50 (data changed this long after the edge)
      marg = ""
      if (have_d) marg = (mode == "setup" ? (tx - td) : (td - tx))
      printf "%.3f,%s,%s,%s,%s,%s,%s,%s,%s,%s\n", m*ns,
             (have_d ? sprintf("%.4f", td*ns) : "none"),
             (have_tx ? sprintf("%.4f", tx*ns) : "none"),
             (tq=="" ? (mode=="setup" ? "not-captured" : "held-no-fall") : sprintf("%.4f", tq*ns)),
             (marg != "" ? sprintf("%.4f", marg*ns) : "n/a"),
             (have_q ? sprintf("%.4f", (tq-tx)*ns) : "n/a"),
             qmin, qmax, v, sprintf("%.3g", sl*ns)}'
    i=$((i+1))
  done
} > "$CSV"

column -s, -t "$CSV" 2>/dev/null || cat "$CSV"

# --------------------------------------------------- bracket from measurements --
# Report the measured spacing RANGE of the passing points and of the failing points.
# A boundary statement is only allowed when both sides exist; otherwise the correct
# conclusion is "boundary not found inside this sweep", not a number.
awk -F, -v mode="$MODE" '
NR > 1 && $5 ~ /^-?[0-9.]+$/ {
  s = $5 + 0
  if ($9 == "PASS") { np++; if (pmin == "" || s < pmin) pmin = s; if (pmax == "" || s > pmax) pmax = s }
  else              { nf++; if (fmin == "" || s < fmin) fmin = s; if (fmax == "" || s > fmax) fmax = s }
}
END {
  printf "MEASURED margin, threshold-to-threshold at VTH = 50%% of VDD, ns:\n"
  printf "  setup: t_CLK50 - t_D50   hold: t_D50 - t_CLK50   (larger is safer)\n"
  printf "  working points: n=%d range [%s, %s]\n", np, \
         (np ? sprintf("%.4f", pmin) : "-"), (np ? sprintf("%.4f", pmax) : "-")
  if (nf > 0) printf "  failing points: n=%d range [%s, %s]\n", nf, \
         sprintf("%.4f", fmin), sprintf("%.4f", fmax)
  else        printf "  failing points: none inside this sweep\n"
  if (np == 0) { print "RESULT: no point produced a measurable margin -- check the checker output"; exit 1 }
  col = (mode == "setup" ? "SETUP" : "HOLD")
  if (nf > 0)
    printf "%s: measured boundary bracketed -- works for margin >= %.4f ns, fails for margin <= %.4f ns\n", \
           col, pmin, fmax
  else
    printf "%s: BOUNDARY NOT FOUND IN CURRENT SWEEP (everything measured inside the scan held/captured)\n", col
  if (mode == "hold") {
    print "HOLD_CHARACTERIZED: NO  (one corner, one VDD, one temperature, one load, one slew;"
    print "  a bracket from a handful of points is not a characterisation, and no hold spec may be"
    print "  derived from it. The 1 ns-slew set in particular never entered the hold region:"
    print "  with the pulse timeline of this simulator the data fall lands about one rise time"
    print "  later than the knob value, so that sweep only probed positive hold margins.)"
  }
}' "$CSV"

echo "PRELIMINARY_CHARACTERIZATION mode=$MODE slew_ns=$(awk -v s="$SLEW" 'BEGIN{printf "%.3g", s*1e9}')  (tt corner, VDD=$V, T=$T, Cload=50fF) -- not a spec"
echo "MARGIN_SWEEP[$MODE/$SLEW]: DONE  csv=$CSV  assert=$ASS"
