#!/usr/bin/env python3
"""ddrv_gen.py -- write the Data Driver channel test decks (transistor level only).

Scope guard: this file writes netlists for ONE channel, never 384 of them, and it never
creates a Virtuoso cell. The 15 uA reference is an ideal current source in the testbench,
which is a TESTBENCH ASSUMPTION -- the shared bias generator is explicitly out of scope.

Candidates (compared, not assumed):
  A_series  output mirror device + a series NMOS switch in the current path (DATA_EN)
  B_gate    output mirror device only; DATA_EN steers the shared reference away and a
            weak bleed holds the mirror gate low, so nothing extra sits in the path
  C_cascode A_series's path plus a cascode device (only reached if A/B are short of
            headroom; a cascode is not used just because it looks better)

Usage:
    python scripts/ddrv_gen.py --candidate A_series --model n18 --l 5e-7 --w 2e-6 \
            --vmax 1.8 --mode dc [--out spectre/generated]
"""

import argparse
import os

PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEADER = """// {name} -- generated by scripts/ddrv_gen.py; one channel of the Micro LED data driver.
// Course requirement (the only formal current target): I_PIXEL_ON = 15 uA, defined as the
//   instantaneous pixel current while the Micro LED is selected and ON, not a frame average.
// Direction: current SINK to VSS. Micro LED Vf and the VLED domain stay NOT DEFINED, so no
//   LED model exists here: V(DATA_OUT) is swept as an independent DC test variable and the
//   answer reported is the output compliance / minimum headroom, never a claimed workload.
// The 15 uA reference is an ideal source -> TESTBENCH ASSUMPTION, not a channel device.
simulator lang=spectre insensitive=yes

include "${{QODER_PDK_LIB}}" section={corner}

parameters IREF=15u VDDV=1.8 RSEN={rsen}

* ---- shared bias branch (not part of the per-channel count) --------------------
* ideal 15 uA into a diode-connected device of the SAME geometry as the output
* device, so the mirror ratio is 1:1 and any error is channel-length modulation
* plus the switch, not a sizing ratio. The diode always sits between its gate node
* and VSS; what differs between candidates is what feeds it.
Mref (vbias vbias vss vss) {model} l={lref} w={wref}
Iref (vdd {feed_top}) isource dc=IREF
"""

CANDIDATES = {
    # output device in series with an enable switch: 2 transistors per channel
    "A_series": """
* ---- channel: candidate A_series ----------------------------------------------
Mout (data_out {vbias} mid vss) {model} l={l} w={w}
Msw  (mid data_en vss vss)      {model} l={lsw} w={wsw}
"""
    ,
    # enable steers the reference current into a dummy branch and a bleed discharges the
    # mirror gate; nothing extra sits in the pixel current path
    "B_gate": """
* ---- channel: candidate B_gate (ONE device carries the pixel current) ---------
Mout (data_out {vbias} vss vss) {model} l={l} w={w}

* shared bias block, not per-channel: the pass device isolates the mirror gate from the
* reference when disabled, the dummy takes the 15 uA while disabled, and the bleed pulls
* the mirror gate to 0 so the output device really turns off.
Msteer  (ref_top data_en {vbias} {vbias}) {model} l={lref} w={wref}
Mdummy  (ref_top data_en_b vss vss)       {model} l={lref} w={wref}
Mbleed  ({vbias} data_en_b vss vss)       {model} l={l} w={bleed_w}
"""
    ,
    # only reached when A/B show the headroom is not enough: the cascode pair carries the
    # pixel current, and it reuses B_gate's gated bias block so the same DATA_EN contract
    # (ON ~= 15 uA, OFF ~= 0) is proven for this topology too, not assumed.
    "C_cascode": """
* ---- channel: candidate C_cascode (2 devices carry the current) --------------
Mout (node_m {vbias} vss vss)   {model} l={l} w={w}
Mcas (data_out vcas node_m vss) {model} l={l} w={w}

* shared bias block, identical to B_gate: pass device, dummy that takes the 15 uA while
* disabled, and a bleed that holds the mirror gate at 0 so the stack really turns off.
Msteer  (ref_top data_en {vbias} {vbias}) {model} l={lref} w={wref}
Mdummy  (ref_top data_en_b vss vss)       {model} l={lref} w={wref}
Mbleed  ({vbias} data_en_b vss vss)       {model} l={l} w={bleed_w}
"""
    ,
    # The enable acts on the cascode gate of each channel; the shared vbias is never
    # switched. Its deck is laid out by build_D(), because it is also the only candidate
    # instantiated twice, for the two-channel independence test.
    "D_local": "",
    # per-channel mirror gate; laid out by build_E() (multi-channel + iprobe support)
    "E_local_gate": "",
}

TAIL = """
* ---- rails, the output test source and a known sense resistor -----------------
* `vss` is tied to the Spectre reference node 0 explicitly: an earlier round of this
* project wasted a whole simulation series on a floating `vss` that Spectre still
* reported as "0 errors".
* IOUT comes from the drop across RSEN, not from `save *:current`: this build answers
* that with SPECTRE-8059/8287 warnings, and shipping a run whose warnings were waved
* away is what the review rules forbid.
Vdd  (vdd 0)      vsource dc=VDDV
Vss  (vss 0)      vsource dc=0
Vout (vsw 0)      vsource dc=0
Rsen (data_out vsw) resistor r=RSEN
{stim}{vcassrc}
save vdd vss vsw data_out vbias data_en data_en_b {extra}

{analysis}
"""

DC = "dc1 dc dev=Vout param=dc start=0 stop={vmax} step={step}"

TRAN = """parameters TD={period}

Vde   (data_en 0)   vsource type=pulse val0=0 val1=VDDV period=TD width=0.5*TD \\
                    delay=0.25*TD rise={slew} fall={slew}
Vdeb  (data_en_b 0) vsource type=pulse val0=VDDV val1=0 period=TD width=0.5*TD \\
                    delay=0.25*TD rise={slew} fall={slew}

tran1 tran stop={stop} step={tstep} maxstep={maxstep}"""

STIM_TRAN = """Vde  (data_en 0) vsource dc=0
"""


RSEN_LINE = "Rsen (data_out vsw) resistor r=RSEN"
IPROBE_LINE = "Ip1 (vsw data_out) iprobe"


def maxstep_of(period, explicit=None):
    """`step=` in a Spectre `tran` statement is the PRINT step; the solver's ceiling is
    `maxstep=`. Left unspecified this build used 18 ns for a 200 ns period -- about five
    samples per enable window, which cannot resolve a mirror-gate RC of the same order, and
    a settling time measured with 18 ns sticks is not a settling time. Cap it at period/200
    and at 5 ns (POC_ASSUMPTION: 5 ns keeps a 40 ns settling on ~8 samples)."""
    if explicit:
        return explicit
    p = float(period)
    return "%.4g" % min(p / 200.0, 5e-9)

# Proven on this build by spectre/current_probe_syntax.scs: `save Ip1` yields the trace
# `Ip1:i` with 0 V across the probe, and `save Mout:1` yields the device terminal current
# as an independent cross-check. `Ip1:current`, `Mout:drain` and `save i(X)` are not
# accepted (warnings / fatal SFE-874), so the forms below are the only ones used.
PROBE_SAVE = "save Ip1:i Mout:1"


def build_E(model, l, w, corner, vmax, step, mode, period, slew, en, en1, channels,
            vout, vout1, toggle, probe, mpass_model, mbleed_model, lpass, wpass,
            lbleed, wbleed, vcas="1.8", maxstep=None, cbias=None, method=None,
            errpreset=None):
    """Candidate E: the accepted core, plus a mirror gate that belongs to the channel.

    VBIAS_SHARED is produced by an always-on reference branch and is touched by no bleed:
    a disabled channel bleeds only its own `vbias_ch`, and the shared node can only be
    reached through a pass device. That is the property the previous two structures lacked
    (C bled the shared node; D shared it directly). The price is two more transistors per
    channel, and the pass device only passes well if its gate overdrive clears the local
    node voltage -- which is why Mpass/Mbleed are sized and family-selected by measurement.
    """
    cb = ""
    if cbias:
        cb = ("\n* Cbias -- TESTBENCH BRACKETING ELEMENT, not part of Candidate E. An ideal "
              "15 uA into a\n* diode-connected device gives VBIAS_SHARED a dynamic impedance "
              "of about 1/gm and no\n* hold capacitance, while a real bias buffer has both. "
              "Sweeping this capacitor answers\n* a question the channel alone cannot: is the "
              "observed inter-channel coupling a property\n* of the gating scheme, or of the "
              "bias network this round deliberately left ideal?\n"
              "Cbias (vbias 0) capacitor c=%s\n" % cbias)
    out = ["""// ddrv_E_local_gate_%s -- generated by scripts/ddrv_gen.py (%d channel(s)).
// Accepted core, unchanged: Mout + Mcas, n33, W=%s L=%s, cascode gate at %s V.
// Rework under test: each channel owns its mirror gate node `vbias_ch`. DATA_EN drives a
// local pass device to VBIAS_SHARED; DATA_EN_B drives a local bleed to VSS. No channel can
// bleed the shared node -- that was the fatal property of the shared-gate structure (C) and
// the residual dynamic coupling of the cascode-gate variant (D).
// Direction: low-side SINK to VSS (ENGINEERING_TOPOLOGY_CHOICE). Vf / VLED: NOT DEFINED, so
// V(DATA_OUT) stays a swept test variable and no LED model is invented here.
// ideal IREF / VCAS / DATA_EN / DATA_EN_B: TESTBENCH ASSUMPTIONS (POC_ASSUMPTION).
simulator lang=spectre insensitive=yes

include "${QODER_PDK_LIB}" section=%s

parameters IREF=15u VDDV=1.8 VCASV=%s

* ---- shared bias: always on, never bled by any channel ------------------------
Mref (vbias vbias vss vss) %s l=%s w=%s
Iref (vdd vbias) isource dc=IREF
%s

* `vss` tied to the Spectre reference node 0 on purpose (AGENTS item 19).
Vdd (vdd 0) vsource dc=VDDV
Vss (vss 0) vsource dc=0
""" % (mode, channels, w, l, vcas, corner, vcas, model, l, w, cb)]

    saves = ["vdd", "vss", "vbias"]
    for i in range(channels):
        # channel 0 keeps the unsuffixed net names (same convention as build_D) so every
        # checker written for the accepted framework applies with no new flag; channel 1
        # adds a "1" suffix and is addressed with --net-suffix 1 / --ch 1.
        s = "" if i == 0 else str(i)
        node = "vbias_ch%s" % s
        out.append("""
* ---- channel %d: 2 core MOS + 2 local gate-control MOS ----------------------
Mcas%s   (data_out%s vcas%s   node_m%s vss) %s      l=%s  w=%s
Mout%s   (node_m%s  %s   vss      vss) %s      l=%s  w=%s
* body tied to the local node because that is the one that can fall to 0 V
Mpass_local%s   (vbias   data_en%s   %s %s) %s l=%s w=%s
Mbleed_local%s (%s data_en_b%s vss   vss)  %s  l=%s w=%s
Vcas%s  (vcas%s  0) vsource dc=VCASV
Vout%s  (vsw%s   0) vsource dc=%s
%s
""" % (i,
       s, s, s, s, model, l, w,
       s, s, node, model, l, w,
       s, s, node, node, mpass_model, lpass, wpass,
       s, node, s, mbleed_model, lbleed, wbleed,
       s, s,
       s, s, (vout if i == 0 else vout1),
       ("Ip%s (vsw%s data_out%s) iprobe" % (chr(49 + i), s, s)) if probe == "iprobe"
       else ("Rsen%s (data_out%s vsw%s) resistor r=1e4" % (s, s, s))))
        saves += ["vsw%s" % s, "data_out%s" % s, "node_m%s" % s, node,
                  "data_en%s" % s, "data_en_b%s" % s, "vcas%s" % s]

    if probe == "iprobe":
        # Ip1 is channel 0's probe, Ip2 channel 1's; `:i` is the trace the parser reads,
        # positive in the direction source -> DATA_OUT, i.e. current absorbed by the sink
        out.append("\nsave %s\n" % " ".join("Ip%s:i" % chr(49 + i)
                                           for i in range(channels)))
        out.append("save %s\n" % ("Mout:1" if channels == 1 else
                                  " ".join("Mout%s:1" % ("" if i == 0 else str(i))
                                           for i in range(channels))))
    out.append("\nsave %s\n" % " ".join(saves))
    if mode == "tran":
        out.append("\nparameters TD=%s\n" % period)
    for i in range(channels):
        s = "" if i == 0 else str(i)
        lvl = en if i == 0 else en1
        pulsing = mode == "tran" and (str(i) in str(toggle).split(","))
        on = "VDDV" if lvl == "1" else "0"
        off = "0" if lvl == "1" else "VDDV"
        if pulsing:
            out.append("""Vde%s  (data_en%s 0)   vsource type=pulse val0=0    val1=VDDV period=TD \\
                     delay=0.25*TD width=0.5*TD rise=%s fall=%s
Vdeb%s (data_en_b%s 0) vsource type=pulse val0=VDDV val1=0    period=TD \\
                     delay=0.25*TD width=0.5*TD rise=%s fall=%s
""" % (s, s, slew, slew, s, s, slew, slew))
        else:
            out.append("Vde%s (data_en%s 0) vsource dc=%s\n" % (s, s, on))
            out.append("Vdeb%s (data_en_b%s 0) vsource dc=%s\n" % (s, s, off))
    if mode == "dc":
        out.append("\ndc1 dc dev=Vout param=dc start=0 stop=%s step=%s\n" % (vmax, step))
    else:
        tran = "tran1 tran stop=%.6g step=%.6g maxstep=%s" % (
            float(period) * 4.5, float(period) / 2000.0, maxstep_of(period, maxstep))
        # `method=` is written only when asked for. Left out, this build derives it from
        # errpreset (default "moderate" -> traponly), which is exactly the production case
        # the A/B test has to be compared against.
        if method:
            tran += " method=%s" % method
        # errpreset is a PACKAGE, not a single tolerance knob: on this build "conservative"
        # sets reltol=1e-4 AND lteratio=10 AND relref=alllocal AND method=gear2only. The
        # method is therefore always pinned explicitly alongside it, and the run header is
        # read back to prove which numbers actually applied.
        if errpreset:
            tran += " errpreset=%s" % errpreset
        out.append("\n%s\n" % tran)
    return "".join(out)


def pulse_problem(period, slew):
    """DATA_EN is defined here as a pulse with width = 0.5*TD and rise = fall = slew. If
    TD < width+rise+fall the enable cannot complete inside one frame, and Spectre does not
    fail: it prints CMI-2210 and silently resets the period, which would quietly replace the
    frame under test with a slower one. Refuse that instead of reporting it as a result."""
    if not (period and slew):
        return None
    p, s = float(period), float(slew)
    need = 0.5 * p + 2 * s
    if p < need:
        return ("period %gs < width+rise+fall = %gs (slew %gs): the enable never completes "
                "in one frame; Spectre CMI-2210 would reset the period" % (p, need, s))
    return None


def build_D(model, l, w, corner, vmax, step, mode, period, slew, rsen, en, en1,
            channels, vout, vout1, toggle, maxstep=None):
    """Candidate D, and the only builder here that can instantiate more than one channel.

    The fix the review asked for: the enable belongs to the channel, so it sits on the
    cascode gate, and the shared `vbias` is never switched. That drops Msteer/Mdummy/
    Mbleed, the ideal VCAS source and DATA_EN_B entirely. Channel 0 keeps the unsuffixed
    net names so every checker written for the accepted measurement framework applies
    unchanged; channel 1 adds `1` suffixes for the independence test only.
    """
    head = ("""// ddrv_D_local_%s -- generated by scripts/ddrv_gen.py (candidate D_local, %d channel(s)).
// Rework of the accepted 15 uA cascode core: same Mout + Mcas, same W/L, same current.
// What changed is only WHERE the enable acts: DATA_EN drives the cascode gate, so each
// channel cuts its own path and the shared VBIAS stays up. The previous structure bled
// the shared gate to 0, which cannot work once channels are switched independently.
// Direction: low-side SINK to VSS (ENGINEERING_TOPOLOGY_CHOICE). Vf / VLED: NOT DEFINED,
// so V(DATA_OUT) is a swept test variable and no LED model exists here.
// The 15 uA reference is an ideal source -> TESTBENCH ASSUMPTION; its 15 uA is shared
// bias overhead while any channel is off, reported but not a blocker this round.
simulator lang=spectre insensitive=yes

include "${QODER_PDK_LIB}" section=%s

parameters IREF=15u VDDV=1.8 RSEN=%s

* ---- shared bias, always on -------------------------------------------------
Mref (vbias vbias vss vss) %s l=%s w=%s
Iref (vdd vbias) isource dc=IREF

* Rails: `vss` is tied to the Spectre reference node 0 explicitly -- a floating vss once
* produced a whole simulation series of "all PMOS working, every NMOS dead" with 0 errors.
Vdd (vdd 0) vsource dc=VDDV
Vss (vss 0) vsource dc=0
""" % (mode, channels, corner, rsen, model, l, w))

    body = []
    for i in range(channels):
        s = "" if i == 0 else str(i)
        body.append("""
* ---- channel %d: the 2 MOS that every channel must repeat ----------------------
Mcas%s (data_out%s data_en%s node_m%s vss) %s l=%s w=%s
Mout%s (node_m%s  vbias     vss     vss) %s l=%s w=%s
Vout%s (vsw%s 0)      vsource dc=%s
Rsen%s (data_out%s vsw%s) resistor r=RSEN
""" % (i, s, s, s, s, model, l, w, s, s, model, l, w, s, s,
       (vout if i == 0 else vout1), s, s, s))

    if mode == "dc":
        for i in range(channels):
            s = "" if i == 0 else str(i)
            lvl = en if i == 0 else en1
            body.append("Vde%s (data_en%s 0) vsource dc=%s\n"
                        % (s, s, "VDDV" if lvl == "1" else "0"))
        analysis = "dc1 dc dev=Vout param=dc start=0 stop=%s step=%s" % (vmax, step)
    else:
        # one channel toggles, the others hold: the independence test is exactly "does a
        # switching neighbour move the current of the channel that stayed on"
        for i in range(channels):
            s = "" if i == 0 else str(i)
            if str(i) in str(toggle).split(","):
                body.append("""Vde%s (data_en%s 0) vsource type=pulse val0=0 val1=VDDV period=TD \\
                    delay=0.25*TD width=0.5*TD rise=%s fall=%s
""" % (s, s, slew, slew))
            else:
                lvl = en if i == 0 else en1
                body.append("Vde%s (data_en%s 0) vsource dc=%s\n"
                            % (s, s, "VDDV" if lvl == "1" else "0"))
        body.append("parameters TD=%s\n" % period)
        analysis = "tran1 tran stop=%s step=%s maxstep=%s" % (
            float(period) * 4.5, float(period) / 2000.0, maxstep_of(period, maxstep))

    saved = ["vdd", "vss", "vsw", "data_out", "vbias", "node_m", "data_en"]
    for i in range(1, channels):
        saved += ["vsw%d" % i, "data_out%d" % i, "node_m%d" % i, "data_en%d" % i]
    tail = "\nsave %s\n\n%s\n" % (" ".join(saved), analysis)
    return head + "".join(body) + tail


def build(cand, model, l, w, corner, vmax, step, mode, lref=None, wref=None,
          lsw=None, wsw=None, bleed_w=None, period=None, slew=None, vcas=None,
          rsen="1e4", en="1", en1="1", channels=1, vout=None, vout1=None,
          toggle="0", probe="rsen", mpass_model="n18", mbleed_model="n18",
          lpass="1e-6", wpass="2e-5", lbleed="1e-6", wbleed="2e-6", maxstep=None,
          cbias=None, method=None, errpreset=None):
    if cand == "E_local_gate":
        return build_E(model, l, w, corner, vmax, step, mode, period, slew, en, en1,
                       int(channels), vout or "0", vout1 or "0", toggle, probe,
                       mpass_model, mbleed_model, lpass, wpass, lbleed, wbleed,
                       vcas or "1.8", maxstep=maxstep, cbias=cbias, method=method,
                       errpreset=errpreset)
    if cand == "D_local":
        return build_D(model, l, w, corner, vmax, step, mode, period, slew, rsen,
                       en, en1, int(channels), vout or "0", vout1 or "0", toggle,
                       maxstep=maxstep)
    lref = lref or l
    wref = wref or w
    lsw = lsw or l
    wsw = wsw or w
    bleed_w = bleed_w or w
    sub = dict(model=model, l=l, w=w, lref=lref, wref=wref, lsw=lsw, wsw=wsw,
               bleed_w=bleed_w, corner=corner, vmax=vmax, step=step, slew=slew,
               vbias="vbias")
    # candidate C's cascode gate is an ideal bias in this round (TESTBENCH ASSUMPTION), the
    # same way the 15 uA reference is; a real bias ladder for it is a later phase.
    vcas_src = "Vcas (vcas 0) vsource dc=%s\n" % (vcas or "1.1")
    # A_series: the ideal source feeds the diode directly. B_gate and C_cascode: it feeds
    # the steering node, and the pass device decides whether the mirror gate sees it.
    feed_top = "vbias" if cand == "A_series" else "ref_top"
    head = HEADER.format(vbias="vbias", model=model, lref=lref, wref=wref,
                         feed_top=feed_top, corner=corner, rsen=rsen,
                         name="ddrv_%s_%s" % (cand, mode))
    body = CANDIDATES[cand].format(**sub)
    if mode == "dc":
        hi, lo = ("VDDV", "0") if en == "1" else ("0", "VDDV")
        stim = ("Vde  (data_en 0)   vsource dc=%s\nVdeb (data_en_b 0) vsource dc=%s\n"
                % (hi, lo))
        analysis = DC.format(vmax=vmax, step=step)
        extra = {"A_series": "mid", "B_gate": "ref_top",
                 "C_cascode": "node_m vcas ref_top"}[cand]
    else:
        stim = ""
        analysis = TRAN.format(period=period, slew=slew, stop=float(period) * 4.5,
                               tstep=float(period) / 2000.0,
                               maxstep=maxstep_of(period, maxstep))
        extra = {"A_series": "mid data_en", "B_gate": "ref_top data_en",
                 "C_cascode": "node_m vcas data_en"}[cand]
    tail = TAIL.format(stim=stim, extra=extra, analysis=analysis,
                       vcassrc=(vcas_src if cand == "C_cascode" else ""), **sub)
    return head + body + tail


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidate", required=True, choices=sorted(CANDIDATES))
    ap.add_argument("--model", default="n18")
    ap.add_argument("--l", default="5e-7")
    ap.add_argument("--w", default="2e-6")
    ap.add_argument("--lref")
    ap.add_argument("--wref")
    ap.add_argument("--lsw")
    ap.add_argument("--wsw")
    ap.add_argument("--bleed-w")
    ap.add_argument("--vcas")
    ap.add_argument("--corner", default="tt")
    ap.add_argument("--vmax", default="1.8")
    ap.add_argument("--step", default="0.02")
    ap.add_argument("--mode", default="dc", choices=("dc", "tran"))
    ap.add_argument("--period", default="2e-7")
    ap.add_argument("--slew", default="1e-9")
    ap.add_argument("--vout", default=None, help="hold V(DATA_OUT) at this value (tran)")
    ap.add_argument("--rsen", default="1e4", help="sense resistor in ohms (POC_ASSUMPTION)")
    ap.add_argument("--en", default="1", choices=("0", "1"),
                    help="DC level applied to DATA_EN (0 proves the OFF state)")
    ap.add_argument("--en1", default="1", choices=("0", "1"), help="DATA_EN1, channel 1")
    ap.add_argument("--channels", default=1, type=int, choices=(1, 2),
                    help="candidate D only: 2 channels share vbias and are switched apart")
    ap.add_argument("--vout1", default="0", help="channel 1 output test voltage")
    ap.add_argument("--toggle", default="0", help="tran: which channels pulse, e.g. 0 or 0,1")
    ap.add_argument("--maxstep", default=None,
                    help="tran: solver maximum timestep (default min(period/200, 5 ns)); "
                         "left unset this build picked 18 ns for a 200 ns period")
    ap.add_argument("--probe", default="rsen", choices=("rsen", "iprobe"),
                    help="how IOUT is observed: a 10k resistor (legacy, burdens the "
                         "circuit by 150 mV at 15 uA) or a zero-drop iprobe")
    ap.add_argument("--mpass-model", default="n18", help="family of the local gate pass device")
    ap.add_argument("--mbleed-model", default="n18", help="family of the local bleed device")
    ap.add_argument("--lpass", default="1e-6")
    ap.add_argument("--wpass", default="2e-5")
    ap.add_argument("--lbleed", default="1e-6")
    ap.add_argument("--wbleed", default="2e-6")
    ap.add_argument("--cbias", default=None,
                    help="candidate E only: capacitance on VBIAS_SHARED (TESTBENCH "
                         "bracketing element, models a real bias buffer's hold capacitance)")
    ap.add_argument("--method", default=None,
                    choices=("traponly", "gear2only", "gear2", "trap", "trapgear2",
                             "euler", "trapeuler"),
                    help="candidate E only: force the transient integration method. "
                         "Unset means the production case: this build derives it from "
                         "errpreset (moderate -> traponly)")
    ap.add_argument("--errpreset", default=None, choices=("liberal", "moderate",
                           "conservative"),
                    help="candidate E only: Spectre accuracy package on the tran "
                         "statement. NOTE it also selects the integration method, so "
                         "always pair it with --method; the run header is read back")
    ap.add_argument("--suffix", default="",
                    help="extra tag when a knob outside l/w changes (keeps decks from "
                         "overwriting each other)")
    ap.add_argument("--out", default="spectre/generated")
    a = ap.parse_args()

    if a.mode == "tran":
        bad = pulse_problem(a.period, a.slew)
        if bad:
            print("DDRV_GEN: REFUSED -- " + bad)
            raise SystemExit(2)

    text = build(a.candidate, a.model, a.l, a.w, a.corner, a.vmax, a.step, a.mode,
                 lref=a.lref, wref=a.wref, lsw=a.lsw, wsw=a.wsw, bleed_w=a.bleed_w,
                 period=a.period, slew=a.slew, vcas=a.vcas, rsen=a.rsen, en=a.en,
                 en1=a.en1, channels=a.channels, vout=a.vout, vout1=a.vout1,
                 toggle=a.toggle, probe=a.probe, mpass_model=a.mpass_model,
                 mbleed_model=a.mbleed_model, lpass=a.lpass, wpass=a.wpass,
                 lbleed=a.lbleed, wbleed=a.wbleed, maxstep=a.maxstep, cbias=a.cbias,
                 method=a.method, errpreset=a.errpreset)
    if a.probe == "iprobe" and a.candidate not in ("D_local", "E_local_gate"):
        # the accepted candidates were measured through a 10k resistor; swapping in a
        # zero-drop iprobe re-measures the same circuit without touching its topology
        text = text.replace(RSEN_LINE, IPROBE_LINE + "\n" + PROBE_SAVE)
    if a.mode == "tran" and a.vout and a.candidate not in ("D_local", "E_local_gate"):
        # D_local takes the vout value as a parameter already; running the legacy textual
        # substitution on top of it turned "dc=0.5" into "dc=0.5.5". The preflight caught
        # it as a read-in error, which is exactly what that gate is for.
        text = text.replace("Vout (vsw 0)      vsource dc=0",
                            "Vout (vsw 0)      vsource dc=%s" % a.vout)
    tag = "%s_%s_%s_l%sw%s" % (a.candidate, a.model, a.corner,
                               str(a.l).replace("e-", "e"), str(a.w).replace("e-", "e"))
    if a.candidate in ("D_local", "E_local_gate"):
        tag += "_ch%d" % a.channels     # without this a 2-channel deck overwrote the 1-channel one
    if a.probe == "iprobe":
        tag += "_iprobe"
    if a.cbias:
        tag += "_cbias" + str(a.cbias)
    if a.method:
        tag += "_m" + a.method
    if a.errpreset:
        tag += "_ep" + a.errpreset
    if a.suffix:
        tag += "_" + a.suffix
    if a.mode == "tran":
        tag += "_T%svout%s" % (str(a.period).replace("e-", "e"), a.vout or "0")
        # the effective maxstep goes into the file name: the earlier rounds' decks used the
        # solver's own 18 ns ceiling, and re-running with a resolved step must not silently
        # overwrite that reviewed evidence
        tag += "_ms%gns" % (float(maxstep_of(a.period, a.maxstep)) * 1e9)
    name = "ddrv_%s.scs" % tag
    outdir = os.path.join(PROJ, a.out)
    if not os.path.isdir(outdir):
        outdir = a.out          # allow an absolute guest path
    path = os.path.join(outdir, name)
    # binary write: this script runs on the guest's Python 2.6 as well as Python 3, and
    # the decks must come out LF on both or the awk/bash readers behave differently.
    data = text if isinstance(text, bytes) else text.encode("utf-8")
    with open(path, "wb") as fh:
        fh.write(data)
    print(path)


if __name__ == "__main__":
    main()
