#!/usr/bin/env python3
"""ddrv_gen.py -- write the Data Driver channel test decks (transistor level only).

Scope guard: this file writes netlists for ONE channel, never 384 of them, and it never
creates a Virtuoso cell. The 15 uA reference is an ideal current source in the testbench,
which is a TESTBENCH ASSUMPTION -- the shared bias generator is explicitly out of scope.

Candidates (compared, not assumed):
  A_series  output mirror device + a series NMOS switch in the current path (DATA_EN)
  B_gate    output mirror device only; DATA_EN steers the shared reference away and a
            weak bleed holds the mirror gate low, so nothing extra sits in the path
  C_cascode A_series's path plus a cascode device (only reached if A/B are short of
            headroom; a cascode is not used just because it looks better)

Usage:
    python scripts/ddrv_gen.py --candidate A_series --model n18 --l 5e-7 --w 2e-6 \
            --vmax 1.8 --mode dc [--out spectre/generated]
"""

import argparse
import os

PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEADER = """// {name} -- generated by scripts/ddrv_gen.py; one channel of the Micro LED data driver.
// Course requirement (the only formal current target): I_PIXEL_ON = 15 uA, defined as the
//   instantaneous pixel current while the Micro LED is selected and ON, not a frame average.
// Direction: current SINK to VSS. Micro LED Vf and the VLED domain stay NOT DEFINED, so no
//   LED model exists here: V(DATA_OUT) is swept as an independent DC test variable and the
//   answer reported is the output compliance / minimum headroom, never a claimed workload.
// The 15 uA reference is an ideal source -> TESTBENCH ASSUMPTION, not a channel device.
simulator lang=spectre insensitive=yes

include "${{QODER_PDK_LIB}}" section={corner}

parameters IREF=15u VDDV=1.8 RSEN={rsen}

* ---- shared bias branch (not part of the per-channel count) --------------------
* ideal 15 uA into a diode-connected device of the SAME geometry as the output
* device, so the mirror ratio is 1:1 and any error is channel-length modulation
* plus the switch, not a sizing ratio. The diode always sits between its gate node
* and VSS; what differs between candidates is what feeds it.
Mref (vbias vbias vss vss) {model} l={lref} w={wref}
Iref (vdd {feed_top}) isource dc=IREF
"""

CANDIDATES = {
    # output device in series with an enable switch: 2 transistors per channel
    "A_series": """
* ---- channel: candidate A_series ----------------------------------------------
Mout (data_out {vbias} mid vss) {model} l={l} w={w}
Msw  (mid data_en vss vss)      {model} l={lsw} w={wsw}
"""
    ,
    # enable steers the reference current into a dummy branch and a bleed discharges the
    # mirror gate; nothing extra sits in the pixel current path
    "B_gate": """
* ---- channel: candidate B_gate (ONE device carries the pixel current) ---------
Mout (data_out {vbias} vss vss) {model} l={l} w={w}

* shared bias block, not per-channel: the pass device isolates the mirror gate from the
* reference when disabled, the dummy takes the 15 uA while disabled, and the bleed pulls
* the mirror gate to 0 so the output device really turns off.
Msteer  (ref_top data_en {vbias} {vbias}) {model} l={lref} w={wref}
Mdummy  (ref_top data_en_b vss vss)       {model} l={lref} w={wref}
Mbleed  ({vbias} data_en_b vss vss)       {model} l={l} w={bleed_w}
"""
    ,
    # only reached when A/B show the headroom is not enough: the cascode pair carries the
    # pixel current, and it reuses B_gate's gated bias block so the same DATA_EN contract
    # (ON ~= 15 uA, OFF ~= 0) is proven for this topology too, not assumed.
    "C_cascode": """
* ---- channel: candidate C_cascode (2 devices carry the current) --------------
Mout (node_m {vbias} vss vss)   {model} l={l} w={w}
Mcas (data_out vcas node_m vss) {model} l={l} w={w}

* shared bias block, identical to B_gate: pass device, dummy that takes the 15 uA while
* disabled, and a bleed that holds the mirror gate at 0 so the stack really turns off.
Msteer  (ref_top data_en {vbias} {vbias}) {model} l={lref} w={wref}
Mdummy  (ref_top data_en_b vss vss)       {model} l={lref} w={wref}
Mbleed  ({vbias} data_en_b vss vss)       {model} l={l} w={bleed_w}
"""
    ,
}

TAIL = """
* ---- rails, the output test source and a known sense resistor -----------------
* `vss` is tied to the Spectre reference node 0 explicitly: an earlier round of this
* project wasted a whole simulation series on a floating `vss` that Spectre still
* reported as "0 errors".
* IOUT comes from the drop across RSEN, not from `save *:current`: this build answers
* that with SPECTRE-8059/8287 warnings, and shipping a run whose warnings were waved
* away is what the review rules forbid.
Vdd  (vdd 0)      vsource dc=VDDV
Vss  (vss 0)      vsource dc=0
Vout (vsw 0)      vsource dc=0
Rsen (data_out vsw) resistor r=RSEN
{stim}{vcassrc}
save vdd vss vsw data_out vbias data_en data_en_b {extra}

{analysis}
"""

DC = "dc1 dc dev=Vout param=dc start=0 stop={vmax} step={step}"

TRAN = """parameters TD={period}

Vde   (data_en 0)   vsource type=pulse val0=0 val1=VDDV period=TD width=0.5*TD \\
                    delay=0.25*TD rise={slew} fall={slew}
Vdeb  (data_en_b 0) vsource type=pulse val0=VDDV val1=0 period=TD width=0.5*TD \\
                    delay=0.25*TD rise={slew} fall={slew}

tran1 tran stop={stop} step={tstep}"""

STIM_TRAN = """Vde  (data_en 0) vsource dc=0
"""


def build(cand, model, l, w, corner, vmax, step, mode, lref=None, wref=None,
          lsw=None, wsw=None, bleed_w=None, period=None, slew=None, vcas=None,
          rsen="1e4", en="1"):
    lref = lref or l
    wref = wref or w
    lsw = lsw or l
    wsw = wsw or w
    bleed_w = bleed_w or w
    sub = dict(model=model, l=l, w=w, lref=lref, wref=wref, lsw=lsw, wsw=wsw,
               bleed_w=bleed_w, corner=corner, vmax=vmax, step=step, slew=slew,
               vbias="vbias")
    # candidate C's cascode gate is an ideal bias in this round (TESTBENCH ASSUMPTION), the
    # same way the 15 uA reference is; a real bias ladder for it is a later phase.
    vcas_src = "Vcas (vcas 0) vsource dc=%s\n" % (vcas or "1.1")
    # A_series: the ideal source feeds the diode directly. B_gate and C_cascode: it feeds
    # the steering node, and the pass device decides whether the mirror gate sees it.
    feed_top = "vbias" if cand == "A_series" else "ref_top"
    head = HEADER.format(vbias="vbias", model=model, lref=lref, wref=wref,
                         feed_top=feed_top, corner=corner, rsen=rsen,
                         name="ddrv_%s_%s" % (cand, mode))
    body = CANDIDATES[cand].format(**sub)
    if mode == "dc":
        hi, lo = ("VDDV", "0") if en == "1" else ("0", "VDDV")
        stim = ("Vde  (data_en 0)   vsource dc=%s\nVdeb (data_en_b 0) vsource dc=%s\n"
                % (hi, lo))
        analysis = DC.format(vmax=vmax, step=step)
        extra = {"A_series": "mid", "B_gate": "ref_top",
                 "C_cascode": "node_m vcas ref_top"}[cand]
    else:
        stim = ""
        analysis = TRAN.format(period=period, slew=slew, stop=float(period) * 4.5,
                               tstep=float(period) / 2000.0)
        extra = {"A_series": "mid data_en", "B_gate": "ref_top data_en",
                 "C_cascode": "node_m vcas data_en"}[cand]
    tail = TAIL.format(stim=stim, extra=extra, analysis=analysis,
                       vcassrc=(vcas_src if cand == "C_cascode" else ""), **sub)
    return head + body + tail


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidate", required=True, choices=sorted(CANDIDATES))
    ap.add_argument("--model", default="n18")
    ap.add_argument("--l", default="5e-7")
    ap.add_argument("--w", default="2e-6")
    ap.add_argument("--lref")
    ap.add_argument("--wref")
    ap.add_argument("--lsw")
    ap.add_argument("--wsw")
    ap.add_argument("--bleed-w")
    ap.add_argument("--vcas")
    ap.add_argument("--corner", default="tt")
    ap.add_argument("--vmax", default="1.8")
    ap.add_argument("--step", default="0.02")
    ap.add_argument("--mode", default="dc", choices=("dc", "tran"))
    ap.add_argument("--period", default="2e-7")
    ap.add_argument("--slew", default="1e-9")
    ap.add_argument("--vout", default=None, help="hold V(DATA_OUT) at this value (tran)")
    ap.add_argument("--rsen", default="1e4", help="sense resistor in ohms (POC_ASSUMPTION)")
    ap.add_argument("--en", default="1", choices=("0", "1"),
                    help="DC level applied to DATA_EN (0 proves the OFF state)")
    ap.add_argument("--suffix", default="",
                    help="extra tag when a knob outside l/w changes (keeps decks from "
                         "overwriting each other)")
    ap.add_argument("--out", default="spectre/generated")
    a = ap.parse_args()

    text = build(a.candidate, a.model, a.l, a.w, a.corner, a.vmax, a.step, a.mode,
                 lref=a.lref, wref=a.wref, lsw=a.lsw, wsw=a.wsw, bleed_w=a.bleed_w,
                 period=a.period, slew=a.slew, vcas=a.vcas, rsen=a.rsen, en=a.en)
    if a.mode == "tran" and a.vout:
        text = text.replace("Vout (vsw 0)      vsource dc=0",
                            "Vout (vsw 0)      vsource dc=%s" % a.vout)
    tag = "%s_%s_%s_l%sw%s" % (a.candidate, a.model, a.corner,
                               str(a.l).replace("e-", "e"), str(a.w).replace("e-", "e"))
    if a.suffix:
        tag += "_" + a.suffix
    if a.mode == "tran":
        tag += "_T%svout%s" % (str(a.period).replace("e-", "e"), a.vout or "0")
    name = "ddrv_%s.scs" % tag
    outdir = os.path.join(PROJ, a.out)
    if not os.path.isdir(outdir):
        outdir = a.out          # allow an absolute guest path
    path = os.path.join(outdir, name)
    # binary write: this script runs on the guest's Python 2.6 as well as Python 3, and
    # the decks must come out LF on both or the awk/bash readers behave differently.
    data = text if isinstance(text, bytes) else text.encode("utf-8")
    with open(path, "wb") as fh:
        fh.write(data)
    print(path)


if __name__ == "__main__":
    main()
