#!/bin/bash
# Probe whether full Virtuoso can run headless on IC617 with this build's own
# non-graphical mechanism (no Xvfb, nothing installed, /etc untouched).
#
#   MODE=nograph   virtuoso -nograph -log L          (SKILL loaded via isolated .cdsinit)
#   MODE=restore   virtuoso -nograph -log L -restore NETLIST_FILE (the "‑restore" form)
#   MODE=nographE  needs a display; run with DISPLAY set (e.g. via cdsXvnc)
#
# Everything stays inside the project: HOME is redirected to $PROJ/home, the .cdsinit
# we need is written THERE (the real /root/.cdsinit is never read or modified), and the
# run directory is $PROJ/skill_run so any scratch files land in the project.
set -u

PROJ="${PROJ:-/root/microled_ai_project}"
IL="${1:-$PROJ/skill/nograph_probe.il}"
TMO="${2:-150}"
MODE="${MODE:-nograph}"
TOKEN="${TOKEN:-VIRTUOSO_NOGRAPH: PASS}"

case "$IL" in
  "$PROJ"/*.il) ;;
  *) echo "REFUSED: SKILL file must live under $PROJ (got $IL)"; exit 9 ;;
esac
[ -f "$IL" ] || { echo "REFUSED: $IL not found"; exit 9; }

CAD_ENV="${CAD_ENV:-/root/qoder_ic617_sandbox/bin/cad_env.sh}"
. "$CAD_ENV" || { echo "FATAL: env load failed"; exit 8; }

RUN="$PROJ/skill_run"
mkdir -p "$RUN" "$PROJ/logs" "$PROJ/skill"
export HOME="$PROJ/home"
mkdir -p "$HOME"
cd "$RUN" || exit 9

STAMP=$(date +%Y%m%d_%H%M%S)
LOG="$RUN/virtuoso_${MODE}_${STAMP}.log"
OUT="$RUN/virtuoso_${MODE}_${STAMP}.stdout"

# An isolated .cdsinit: load the probe, then leave. Only written under $PROJ/home.
if [ "$MODE" != "restore" ]; then
  cat > "$HOME/.cdsinit" <<EOF
;; generated by run_virtuoso.sh -- isolated probe init, not the user's real cdsinit
load("$IL")
exit()
EOF
fi

case "$MODE" in
  nograph)  CMD=(virtuoso -nograph -log "$LOG") ;;
  restore)  CMD=(virtuoso -nograph -log "$LOG" -restore "$IL") ;;
  nographE) CMD=(virtuoso -nographE -log "$LOG") ;;
  *) echo "usage: MODE=nograph|restore|nographE"; exit 9 ;;
esac

echo "RUN mode=$MODE timeout=${TMO}s display=[${DISPLAY:-}] cwd=$PWD home=$HOME"
echo "CMD ${CMD[*]}"
start=$(date +%s)
timeout "$TMO" "${CMD[@]}" > "$OUT" 2>&1
rc=$?
echo "RESULT rc=$rc elapsed=$(( $(date +%s) - start ))s"
echo "LOG $LOG"
echo "STDOUT $OUT"

combined="$OUT"
[ -s "$LOG" ] && combined="$LOG $OUT"

if grep -qsF "$TOKEN" $combined; then
  echo "TOKEN_FOUND yes"
  echo "----- relevant log lines -----"
  grep -aE "VIRTUOSO_NOGRAPH|engine=|home=|pwd=|display=|has_|Error|error" $combined | head -20
  echo "VIRTUOSO_NOGRAPH: PASS"
  exit 0
fi

echo "TOKEN_FOUND no"
echo "----- raw stdout (head 25) -----"
head -25 "$OUT" 2>/dev/null
echo "----- raw stdout (tail 25) -----"
tail -25 "$OUT" 2>/dev/null
if [ -s "$LOG" ]; then
  echo "----- log head/tail -----"
  head -12 "$LOG"; echo "..."; tail -12 "$LOG"
fi
echo "VIRTUOSO_NOGRAPH: FAIL"
exit 1
