#!/usr/bin/env python
# SCH-1 Part C: generate the SKILL port table for the DFF cellview.
#
# The port NAMES are read out of the accepted golden netlist's `subckt` header, so the pin list
# cannot drift from the cell that was reviewed. The DIRECTIONS are the SCH-1 spec's assignment
# (d, clk = input; q, qbar = output; vdd, vss = inputOutput); a Spectre subckt header carries no
# direction information, so that mapping is stated here instead of being inferred.
#
# Usage: python scripts/sch1_gen_ports.py <golden.scs> <out.il>
import re
import sys

scs, out = sys.argv[1], sys.argv[2]
text = open(scs).read()

m = re.search(r"^subckt\s+(\S+)\s*\(([^)]*)\)", text, re.M)
if not m:
    sys.stderr.write("FAIL: no `subckt name (ports)` header found in %s\n" % scs)
    sys.exit(5)
src_cell, ports = m.group(1), m.group(2).split()

DIRECTIONS = {"d": "input", "clk": "input", "q": "output", "qbar": "output",
              "vdd": "inputOutput", "vss": "inputOutput"}
unknown = [p for p in ports if p not in DIRECTIONS]
if unknown:
    sys.stderr.write("FAIL: ports with no stated direction: %s\n" % " ".join(unknown))
    sys.exit(5)

lines = [
    ";; GENERATED by scripts/sch1_gen_ports.py from %s -- do not edit by hand" % scs,
    ";; source cell name in that netlist: %s" % src_cell,
    ";; port names: parsed from the subckt header. directions: SCH-1 spec assignment.",
    "sch1PortTable = list(",
]
lines += ['    list("%s" "%s")' % (p, DIRECTIONS[p]) for p in ports]
lines += [")",
          # the double backslash matters: the emitted SKILL file must contain the two characters
          # \n inside its string literal, not a real line break inside it
          'printf("GEN-PORTS count=%L\\n" length(sch1PortTable))']
open(out, "w").write("\n".join(lines) + "\n")
sys.stdout.write("GEN_PORT_SOURCE_CELL=%s GEN_PORTS=%s\n" % (src_cell, " ".join(ports)))
