#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""SCH-2 Part I fallback: build a Spectre netlist from the schematic readback alone.

Every number written here is read off the OA database by skill/sch2_readback.il: the instance name,
the master, the model property, the net bound to each master terminal, and the resolved length and
width. This script deliberately never opens spectre/C2MOS_DFF.scs, because the previous round of
this project produced a "netlist from the schematic" whose W/L were still the netlist's expressions
plus the golden's defaults -- which is exactly how a schematic carrying the PDK's default geometry
stayed hidden behind a passing simulation.

Usage: python scripts/sch2_netlist_from_readback.py <readback.log> <cell> <out.scs>
"""
from __future__ import print_function

import io
import re
import sys

PAIR = re.compile(r'(\w+)=(?:"([^"]*)"|(\((?:[^()]|\([^()]*\))*\))|([^\s]+))')
PIN_ORDER = ("d", "clk", "q", "qbar", "vdd", "vss")


def parse(line):
    out = {}
    for m in PAIR.finditer(line):
        v = m.group(2)
        if v is None:
            v = m.group(3) if m.group(3) is not None else m.group(4)
        out[m.group(1)] = v.strip()
    return out


def number(text):
    s = str(text).strip()
    while s.startswith("(") and s.endswith(")"):
        s = s[1:-1].strip()
    return s.strip('"')


def main():
    log, cell, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    rows, netpins = [], []
    for line in io.open(log, encoding="utf-8", errors="replace"):
        if "RD-ROW" in line:
            rows.append(parse(line))
        elif "RD-NETPIN" in line:
            r = parse(line)
            if r.get("net"):
                netpins.append(r["net"])

    bad = []
    body = []
    for r in rows:
        l_txt, w_txt = number(r.get("num_l")), number(r.get("num_w"))
        for key, val in (("l", l_txt), ("w", w_txt)):
            if not re.match(r"^-?\d+\.?\d*(?:[eE][-+]?\d+)?$", val):
                bad.append("%s: %s is not a resolved number (%s)" % (r.get("inst"), key, val))
        nets = [r.get("D"), r.get("G"), r.get("S"), r.get("B")]
        if any(n in (None, "UNCONNECTED", "NO-PIN") for n in nets):
            bad.append("%s: terminal not bound %s" % (r.get("inst"), nets))
        body.append("  %s (%s %s %s %s) %s l=%s w=%s"
                    % (r.get("inst"), nets[0], nets[1], nets[2], nets[3],
                       r.get("model"), l_txt, w_txt))

    ports = [p for p in PIN_ORDER if p in netpins]
    if len(ports) != len(PIN_ORDER):
        bad.append("port pins found %s, expected %s" % (" ".join(sorted(netpins)), " ".join(PIN_ORDER)))
    unknown = sorted(set(netpins) - set(PIN_ORDER))
    if unknown:
        bad.append("unexpected pinned nets: %s" % " ".join(unknown))

    out = ["; SCH-2: netlist rebuilt from the OA cellview %s (readback rows only)." % cell,
           "; Input file: %s -- generated by skill/sch2_readback.il against the saved schematic." % log,
           "; l= and w= are the numbers the database itself resolved; nothing here is read from",
           "; spectre/C2MOS_DFF.scs.",
           "simulator lang=spectre insensitive=yes",
           "",
           "subckt %s (%s)" % (cell, " ".join(ports))]
    out += sorted(body)
    out += ["ends %s" % cell, ""]
    io.open(out_path, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")

    print("READBACK_ROWS: %d" % len(rows))
    print("PORTS_FROM_PINS: %s" % " ".join(ports))
    print("NETLIST_FROM_READBACK: %s" % out_path)
    for b in bad:
        print("READBACK_PROBLEM: %s" % b)
    verdict = "PASS" if (len(rows) == 18 and not bad) else "FAIL"
    print("NETLIST_FROM_READBACK_BUILD: %s" % verdict)
    return 0 if verdict == "PASS" else 1


sys.exit(main())
