#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""SCH-2: emit the SKILL table that writes golden sizes onto schematic instances.

Input is the golden parameter table produced by scripts/sch2_golden_params.py, i.e. numbers already
resolved from the netlist's design variables -- this script never reads a schematic and never
invents a size.

Every emitted string must parse back to the same metre value through the same rule the CDF uses
(cdfParseFloatString accepts "200n", "2u", "2e-6"); if a value cannot be written exactly in that
form the generator stops, because a rounded size would let a wrong schematic look right.

Usage: python scripts/sch2_gen_param_skill.py <golden.csv> <out.il>
"""
from __future__ import print_function

import io
import re
import sys

SUFFIX = [("u", 1e-6), ("n", 1e-9), ("p", 1e-12)]


def as_metric(value):
    """Render metres as the shortest exact Spectre-style length string."""
    for suffix, scale in SUFFIX:
        scaled = value / scale
        if abs(scaled - round(scaled)) < 1e-12 and round(scaled) > 0:
            return "%d%s" % (int(round(scaled)), suffix), int(round(scaled)) * scale
    text = "%.12g" % value
    return text, float(text)


def main():
    csv_in, out_il = sys.argv[1], sys.argv[2]
    lines = io.open(csv_in, encoding="utf-8", errors="replace").read().strip().split("\n")
    header = lines[0].split(",")
    rows = [dict(zip(header, l.split(","))) for l in lines[1:]]

    out = [";; GENERATED by scripts/sch2_gen_param_skill.py from %s -- do not edit by hand" % csv_in,
           ";; one row per MOS: instance, model, length string, total-width string, finger-width string,",
           ";; fingers, multiplier. Values come from the golden netlist only.",
           "sch1ParamTable = list("]
    problems = []
    for r in rows:
        l_m = float(r["golden_L_m"])
        w_m = float(r["golden_W_m"])
        l_str, l_back = as_metric(l_m)
        w_str, w_back = as_metric(w_m)
        if abs(l_back - l_m) > 1e-18 or abs(w_back - w_m) > 1e-18:
            problems.append("%s: %.9g -> %s -> %.9g is not exact" % (r["instance_name"], l_m, l_str, l_back))
        # fingers=1 in the golden, so finger width and total width must be the same number
        fw_str = w_str
        out.append('    list("%s" "%s" "%s" "%s" "%s" "%s")'
                   % (r["instance_name"], r["model"], l_str, w_str, fw_str, "1"))
    out += [")",
            'printf("GEN-PARAM-ROWS count=%L\\n" length(sch1ParamTable))']
    for p in problems:
        print("ROUNDTRIP_PROBLEM: %s" % p)
    if problems:
        print("SCH2_PARAM_TABLE_EMIT: FAIL")
        return 1
    io.open(out_il, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print("SCH2_PARAM_TABLE: %s rows=%d" % (out_il, len(rows)))
    print("SCH2_PARAM_TABLE_EMIT: PASS")
    return 0


sys.exit(main())
