#!/bin/bash
# SCH-3 section 9: import generated sub-circuit netlists as real, editable OA schematics using
# Cadence's own netlist->schematic importer (spiceIn / Analog Schematic Generation).
#
# Why the same tool as SCH-1: on this build the Schematic Editor SKILL package is not registered
# for a batch session (schCreate/schCreateWire/schCheck undefined, measured), while spiceIn produces
# a Composer schematic whose connectivity comes out of the netlist file rather than out of anyone's
# head. SCH-1 proved the route (72/72 net-to-pin bindings); SCH-2 proved what it does NOT do -- it
# leaves sizes in a CDF-invisible property -- so the import is only step one and the integrity gate
# in scripts/sch_parameter_integrity_check.py is the verdict, not this script.
#
# Guards (all measured failure modes, kept so they are not re-attempted):
#   * refuses to run on anything outside $PROJ/spectre/import
#   * refuses if ANY target cell already exists in the library -- nothing is ever overwritten
#   * refuses if a listed cell is not present as a `subckt' header, so a silently missing cell
#     cannot turn into "the schematic is smaller than the golden"
#   * overwriteCells NONE, so the tool itself also refuses to clobber
#
# Usage:
#   TOP=sch3_top CELLS="data_sink_1ch data_bias_ref" \
#     bash scripts/sch3_asg_import.sh spectre/import/sch3_top.scs
set -u

PROJ="${PROJ:-/root/microled_ai_project}"
WORK="$PROJ/cadence_work"
LIB="${LIB:-microled_cells}"
TOP="${TOP:?usage: TOP=<topCell> CELLS=<cell list> sch3_asg_import.sh <netlist relative to PROJ>}"
CELLS="${CELLS:-}"
SRCREL="${1:?usage: TOP=<topCell> CELLS=<cell list> sch3_asg_import.sh <netlist relative to PROJ>}"

NL="$PROJ/$SRCREL"
case "$SRCREL" in
  spectre/import/*.scs) ;;
  *) echo "REFUSE: import netlist must live under spectre/import/ (got $SRCREL)"; exit 9 ;;
esac
[ -r "$NL" ] || { echo "REFUSE: import netlist unreadable: $NL"; exit 9; }

IN="$WORK/asg_in"
LOGD="$WORK/logs"
STAMP=$(date +%Y%m%d_%H%M%S)
ASLOG="$LOGD/asg_spiceIn_sch3_$STAMP.log"
mkdir -p "$IN" "$LOGD"

for C in $TOP $CELLS; do
  if [ -e "$WORK/$LIB/$C" ]; then
    echo "REFUSE: $LIB/$C already exists -- nothing is overwritten. Inspect it, do not re-run."
    exit 7
  fi
done
for C in $CELLS; do
  grep -qE "^subckt[[:space:]]+${C}([[:space:]]|\()" "$NL" || {
    echo "REFUSE: $NL has no 'subckt $C' header -- that cell would silently not be created"
    exit 6
  }
  grep -qE "^ends[[:space:]]+${C}([[:space:]]|\$)" "$NL" || {
    echo "REFUSE: subckt $C has no matching ends statement"
    exit 6
  }
done
grep -qE "^subckt[[:space:]]+${TOP}([[:space:]]|\()" "$NL" && {
  echo "REFUSE: top cell $TOP is also a subckt in the file (SPICEIN-77)"
  exit 6
} || true

MOSLINES=$(grep -cE '^[[:space:]]*M[A-Za-z_][A-Za-z_0-9]*[[:space:]]*\(' "$NL")
SUBCKTS=$(grep -cE '^subckt[[:space:]]' "$NL")
echo "IMPORT_NETLIST=$NL TOP=$TOP CELLS=$CELLS SUBCKTS=$SUBCKTS MOS_LINES=$MOSLINES"

PARAM="$IN/${TOP}_param.il"
cat > "$PARAM" <<EOF
;; generated by scripts/sch3_asg_import.sh -- plumbing only, no W/L, no model, no connectivity
spiceInParams = list(nil
    'topCell         "$TOP"
    'language        "SPECTRE"
    'netlistFile     "$NL"
    'outputLib       "$LIB"
    'refLibList      "smic18mmrf analogLib"
    'outputViewType  "schematic"
    'outputViewName  "schematic"
    'simName         "spectre"
    'outputSimName   "spectre"
    'overwriteCells  "NONE"
    'logFile         "$ASLOG"
)
EOF
echo "PARAM_FILE=$PARAM"

# shellcheck disable=SC1091
. "$PROJ/skill/cad_env.sh" || { echo "FATAL: cadence env load failed"; exit 8; }
cd "$WORK" || exit 9
[ -n "$(command -v spiceIn)" ] || { echo "FATAL: spiceIn not on the Cadence PATH"; exit 8; }

timeout "${TMO:-300}" spiceIn -param "$PARAM"
rc=$?
echo "ASG rc=$rc"
[ -f "$WORK/spiceIn.log" ] && cp -f "$WORK/spiceIn.log" "$LOGD/asg_cwdlog_sch3_$STAMP.log"
echo "ASG_LOG=$ASLOG"
echo "--- log tail ---"
tail -25 "$ASLOG" 2>&1
echo "--- error/warning scan ---"
grep -icE 'error|\*E\)|not found|cannot|unable' "$ASLOG" | sed 's/^/ASG_PROBLEM_LINES: /'
echo "--- library contents ---"
ls -1 "$WORK/$LIB" 2>&1 | head -20
for C in $TOP $CELLS; do
  if [ -d "$WORK/$LIB/$C/schematic" ]; then
    echo "ASG_SCHEMATIC_DIR=yes cell=$C"
    ls -l "$WORK/$LIB/$C/schematic" | head -4
  else
    echo "ASG_SCHEMATIC_DIR=no cell=$C"
  fi
done
[ "$rc" -eq 0 ] || exit 1
exit 0
